variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_REGISTRY: "docker.io"
  DOCKER_REGISTRY_IMAGE: "${DOCKER_REGISTRY}/fengxsong/${CI_PROJECT_NAME}"

stages:
  - "build"

build image:
  stage: build
  tags:
    - sre
  only:
    - master
    - main
    - tags
  services:
    - name: docker:19.03.12-dind
      command:
        - --registry-mirror=https://dockerhub.tencentcloudcr.com
  image: docker:19.03.12
  script:
    - docker login -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - test -z $CI_COMMIT_TAG && export CI_TAG=${CI_COMMIT_SHORT_SHA} || CI_TAG=${CI_COMMIT_TAG}
    - docker build -t ${DOCKER_REGISTRY_IMAGE}:${CI_TAG} .
    - docker push ${DOCKER_REGISTRY_IMAGE}:${CI_TAG}